version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-tracker-dev
    ports:
      - '5555:5000'
    volumes:
      - ./:/code/
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'

  database:
    image: postgres:12
    container_name: article-tracker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=article_data
    volumes:
      - ./db_mount:/var/lib/postgresql/data